---

local_download_dir: "{{ playbook_dir }}/download"
local_resource_dir: "{{ playbook_dir }}/resource"
local_binary_dir: "{{ playbook_dir }}/resource/bin"
local_conf_dir: "{{ playbook_dir }}/conf"

package_type: docker

# image repo url
kubernetes_image_repo: "registry.aliyuncs.com/google_containers"
flannel_image_repo: "quay.io/coreos"

# iamge versions
etcd_version: 3.3.15-0
kube_version: v1.16.0
coredns_version: 1.6.2
pause_version: 3.1
flannel_version: v0.12.0-amd64