---
# init tasks main

- name: "Create general directories"
  file:
    path: "{{ project_dir }}/{{ item }}"
    state: directory
  with_items:
    - group_vars
    - host_vars
    - library

- name: "Create directory structure for roles"
  file:
    path: "{{ project_dir }}/roles/{{ item[0] }}/{{ item[1] }}"
    state: directory
  with_nested:
    - "{{ project_roles }}"
    - [ 'defaults', 'files', 'handlers', 'meta', 'tasks', 'templates']

- name: "Create group_vars/all.yml"
  copy:
    src: "all.yml"
    dest: "{{ project_dir }}/group_vars/{{ item }}.yml"
  with_items:
    - all

- name: "Create inventory files"
  copy:
    src: inventory.ini
    dest: "{{ project_dir }}/{{ item }}.ini"
  with_items:
    - production
    - staging
    - inventory

- name: "Create deploy playbook files"
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ project_dir }}/{{ item }}.yml"
  with_items:
    - deploy
    - update
    - local_prepare

- name: "Create run scripts"
  copy:
    src: "{{ item }}.sh"
    dest: "{{ project_dir }}/{{ item }}.sh"
    mode: 0755
  with_items:
    - deploy
    - update
    - local_prepare

- name: "Create general roles"
  copy:
    src: "{{ item }}"
    dest: "{{ project_dir }}/roles/"
  with_items:
    - local
    - download
    - common_dir
    - apt
    - pip
    - systemd
    - upconf
    - docker

- name: "Create main.yml in directory structure for roles"
  template:
      src: "{{ item[1] }}.yml.j2"
      dest: "{{ project_dir }}/roles/{{ item[0] }}/{{ item[1] }}/main.yml"
  with_nested:
    - "{{ project_roles }}"
    - [ 'defaults', 'handlers', 'meta', 'tasks']

- name: "Create other task file"
  template:
      src: "{{ item[1] }}.yml.j2"
      dest: "{{ project_dir }}/roles/{{ item[0] }}/tasks/{{ item[1] }}.yml"
  with_nested:
    - "{{ project_roles }}"
    - [ 'apt_deployment', 'binary_deployment', 'docker_deployment', 'compile_deployment', 'configure', 'systemd_supervision']

- name: "Create template file"
  template:
      src: "run_{{ item[1] }}.sh.j2"
      dest: "{{ project_dir }}/roles/{{ item[0] }}/templates/run_{{ item[0] }}_{{ item[1] }}.sh.j2"
  with_nested:
    - "{{ project_roles }}"
    - [ 'binary', 'docker']

- name: "Add ansible config"
  copy:
    src: ansible.cfg
    dest: "{{ project_dir }}/ansible.cfg"

- name: "Add requirements file"
  copy:
    src: requirements.txt
    dest: "{{ project_dir }}/requirements.txt"
